services:
  redis:
    build: redis
    command: >
      redis-server /usr/local/etc/redis/redis.conf 
      --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  
  backend:
    build: backend
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis:6379
      - AUTH_URL=${AUTH_URL}
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:4000/ || exit 1" ]
      start_period: 5s


  frontend:
    build: 
      context: frontend
      target: production
      args:
        - VITE_AUTH_URL=${AUTH_URL}
        - VITE_AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
    depends_on:
      - redis
      - backend
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/ || exit 1" ]
      start_period: 5s

  nginx:
    build: nginx
    depends_on:
      - redis
      - frontend
      - backend
    restart: unless-stopped