services:
  backend:
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app
          ignore:
            - node_modules/

  frontend:
    build:
      context: frontend
      target: development
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/

  nginx:
    ports:
      - 80:80