################################## NETWORK #####################################

# Bind to all interfaces so other containers on the can connect
bind 0.0.0.0

# Standard Redis port
port 6379

# Close the connection after a client is idle for N seconds (0 to disable)
timeout 0

# TCP keepalive to help detect dead peers
tcp-keepalive 300

################################# SECURITY #####################################

# Require a password for all connections; overriden via command line in docker-compose.yml
requirepass ${REDIS_PASSWORD}

# Protected mode is 'yes' by default, but it requires 'bind' or a password.
protected-mode yes

################################ SNAPSHOTTING  ################################

# Save the DB to disk (useful even for chat to survive small crashes)
# Save every 900s if 1 key changed, 300s if 10 keys changed, 60s if 10k keys changed.
save 900 1
save 300 10
save 60 10000

# The filename and working directory for snapshots
dbfilename dump.rdb
dir /data

############################## APPEND ONLY MODE ###############################

appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

################################## MEMORY ######################################

# Set a limit so Redis doesn't crash the VM if it runs out of RAM
maxmemory 256mb
maxmemory-policy allkeys-lru